Repository AChillFeeder/ProjetSansNom-Front, pull requests merged in 2025-03, with the labels that each got.

#44 Dev
  src/Authentification/Connexion.css
  src/Authentification/Connexion.js
  src/Authentification/Inscription.css
  src/Authentification/Inscription.js
  src/index.js
Labels: bug-fix

#49 fix url
  src/HealthCheck/HealthCheck.js
Labels: bug-fix

#48 feature: CRUD
  package-lock.json
  package.json
  public/index.html
  src/CRUD/AjoutModif.css
  src/CRUD/AjoutModif.js
  src/CRUD/Consultation.css
  src/CRUD/Consultation.js
  src/CRUD/Suppression.css
  src/CRUD/Suppression.js
  src/index.js
Labels: Fonctionnalité

#50 update API endpoints to use a constant for the base URL
  src/Authentification/Connexion.js
  src/Authentification/Inscription.js
  src/Constante.js
Labels: Fonctionnalité

#51 changement url de base
  src/Constante.js
  src/HealthCheck/HealthCheck.js
Labels: Fonctionnalité

#55 ajout des fichiers Accueil.css et Accueil.js vides
  package-lock.json
  package.json
  src/Accueil/Accueil.css
  src/Accueil/Accueil.js
  src/Authentification/Connexion.js
  src/Authentification/Inscription.css
  src/Authentification/Inscription.js
  src/Messagerie/Messagerie.css
  src/Messagerie/Messagerie.js
  src/index.js
Labels: Fonctionnalité

#59 Refactor AjoutModif component to handle form data more efficiently an…
  src/CRUD/AjoutModif.js
  src/CRUD/Consultation.js
Labels: bug-fix, Fonctionnalité
